"""
System prompts, templates, and medical disclaimers.

This module provides all prompts and templates for the LangGraph agent workflow:
- System prompts for each agent node (Query Analyzer, Risk Assessor, Reasoner, Response Generator)
- Response templates that vary by risk level
- Guardrails to ensure AI safety and compliance
- Medical disclaimers required on all responses
"""

from agent.prompts.disclaimers import (
    INLINE_DISCLAIMERS,
    LIMITATION_DISCLAIMER,
    PREGNANCY_DISCLAIMER,
    RESEARCH_CITATION_DISCLAIMER,
    RESPONSE_FOOTER,
    SENSITIVITY_DISCLAIMER,
    SHORT_DISCLAIMER,
    STANDARD_MEDICAL_DISCLAIMER,
    URGENT_DISCLAIMER,
    format_complete_disclaimer,
    format_response_footer,
    get_contextual_disclaimers,
    get_disclaimer_for_risk_level,
    get_inline_disclaimer,
)
from agent.prompts.guardrails import (
    DIAGNOSIS_PATTERNS,
    GUARDRAIL_SYSTEM_PROMPT_ADDITION,
    HARMFUL_ADVICE_PATTERNS,
    HEDGING_PHRASES,
    OUT_OF_SCOPE_PATTERNS,
    PRESCRIPTION_PATTERNS,
    SAFE_LANGUAGE_ALTERNATIVES,
    VAGINAL_HEALTH_TOPICS,
    GuardrailResult,
    GuardrailViolation,
    ViolationType,
    check_diagnosis_violations,
    check_grounding,
    check_harmful_advice,
    check_missing_disclaimer,
    check_prescription_violations,
    check_scope_violations,
    sanitize_response,
    validate_response,
)
from agent.prompts.response_templates import (
    CONCERNING_RESPONSE_TEMPLATE,
    DOCTOR_DISCUSSION_POINTS,
    EMERGENCY_DISCUSSION_POINTS,
    MONITOR_RESPONSE_TEMPLATE,
    MONITORING_STEPS,
    NORMAL_RESPONSE_TEMPLATE,
    PH_ASSESSMENT_PHRASES,
    RESPONSE_TEMPLATES,
    RISK_LEVEL_CONFIGS,
    URGENT_RESPONSE_TEMPLATE,
    WELLNESS_TIPS_NORMAL,
    RiskLevel,
    RiskLevelConfig,
    get_ph_assessment_phrase,
    get_response_template,
    get_risk_config,
)
from agent.prompts.system_prompts import (
    BASE_MEDICAL_CONTEXT,
    QUERY_ANALYZER_SYSTEM_PROMPT,
    QUERY_ANALYZER_USER_TEMPLATE,
    REASONER_SYSTEM_PROMPT,
    REASONER_USER_TEMPLATE,
    RESPONSE_GENERATOR_SYSTEM_PROMPT,
    RESPONSE_GENERATOR_USER_TEMPLATE,
    RISK_ASSESSOR_SYSTEM_PROMPT,
    RISK_ASSESSOR_USER_TEMPLATE,
    SYSTEM_PROMPTS,
    USER_TEMPLATES,
)

__all__ = [
    # System Prompts
    "BASE_MEDICAL_CONTEXT",
    "QUERY_ANALYZER_SYSTEM_PROMPT",
    "QUERY_ANALYZER_USER_TEMPLATE",
    "RISK_ASSESSOR_SYSTEM_PROMPT",
    "RISK_ASSESSOR_USER_TEMPLATE",
    "REASONER_SYSTEM_PROMPT",
    "REASONER_USER_TEMPLATE",
    "RESPONSE_GENERATOR_SYSTEM_PROMPT",
    "RESPONSE_GENERATOR_USER_TEMPLATE",
    "SYSTEM_PROMPTS",
    "USER_TEMPLATES",
    # Response Templates
    "RiskLevel",
    "RiskLevelConfig",
    "RISK_LEVEL_CONFIGS",
    "NORMAL_RESPONSE_TEMPLATE",
    "MONITOR_RESPONSE_TEMPLATE",
    "CONCERNING_RESPONSE_TEMPLATE",
    "URGENT_RESPONSE_TEMPLATE",
    "RESPONSE_TEMPLATES",
    "WELLNESS_TIPS_NORMAL",
    "MONITORING_STEPS",
    "DOCTOR_DISCUSSION_POINTS",
    "EMERGENCY_DISCUSSION_POINTS",
    "PH_ASSESSMENT_PHRASES",
    "get_response_template",
    "get_risk_config",
    "get_ph_assessment_phrase",
    # Guardrails
    "ViolationType",
    "GuardrailViolation",
    "GuardrailResult",
    "PRESCRIPTION_PATTERNS",
    "DIAGNOSIS_PATTERNS",
    "OUT_OF_SCOPE_PATTERNS",
    "HARMFUL_ADVICE_PATTERNS",
    "SAFE_LANGUAGE_ALTERNATIVES",
    "HEDGING_PHRASES",
    "VAGINAL_HEALTH_TOPICS",
    "GUARDRAIL_SYSTEM_PROMPT_ADDITION",
    "check_prescription_violations",
    "check_diagnosis_violations",
    "check_scope_violations",
    "check_harmful_advice",
    "check_missing_disclaimer",
    "check_grounding",
    "validate_response",
    "sanitize_response",
    # Disclaimers
    "STANDARD_MEDICAL_DISCLAIMER",
    "SHORT_DISCLAIMER",
    "URGENT_DISCLAIMER",
    "RESEARCH_CITATION_DISCLAIMER",
    "PREGNANCY_DISCLAIMER",
    "SENSITIVITY_DISCLAIMER",
    "LIMITATION_DISCLAIMER",
    "INLINE_DISCLAIMERS",
    "RESPONSE_FOOTER",
    "get_disclaimer_for_risk_level",
    "get_contextual_disclaimers",
    "format_complete_disclaimer",
    "get_inline_disclaimer",
    "format_response_footer",
]
