"""
Medical Disclaimers

Standard disclaimers that must be included in all responses.
These ensure users understand the limitations of AI-based health information.
"""

from typing import Final


# =============================================================================
# Standard Disclaimers
# =============================================================================

STANDARD_MEDICAL_DISCLAIMER: Final[str] = """---

**Medical Disclaimer**

This information is for educational purposes only and is not intended as a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified healthcare provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read here.

If you think you may have a medical emergency, call your doctor or emergency services immediately. Reliance on any information provided by this service is solely at your own risk."""


SHORT_DISCLAIMER: Final[str] = """⚕️ *This is health information, not medical advice. Please consult a healthcare provider for diagnosis and treatment.*"""


URGENT_DISCLAIMER: Final[str] = """---

**⚠️ Important Medical Notice**

The information provided here suggests you may benefit from prompt medical evaluation. This AI system cannot diagnose conditions or provide treatment. Please contact a healthcare provider or visit an urgent care facility as soon as possible.

If you are experiencing severe symptoms such as high fever, severe pain, or heavy bleeding, please seek emergency medical care immediately.

This information is for educational purposes only and does not replace professional medical evaluation."""


RESEARCH_CITATION_DISCLAIMER: Final[str] = """---

*The information above is derived from peer-reviewed research papers. However, medical knowledge evolves, and individual circumstances vary. A healthcare provider can help interpret how this research applies to your specific situation.*"""


# =============================================================================
# Contextual Disclaimers
# =============================================================================

PREGNANCY_DISCLAIMER: Final[str] = """---

**Pregnancy Notice**

If you are pregnant or think you may be pregnant, it is especially important to consult with your healthcare provider about any vaginal health concerns. Changes in vaginal pH and symptoms during pregnancy may have different implications and require specialized care.

This information is not a substitute for prenatal care."""


SENSITIVITY_DISCLAIMER: Final[str] = """---

**A Note on Your Health Journey**

We understand that discussing vaginal health can feel personal and sometimes uncomfortable. Your health matters, and seeking information is an important step. Remember that many people experience similar concerns, and healthcare providers are trained to help with these issues professionally and confidentially."""


LIMITATION_DISCLAIMER: Final[str] = """---

**AI Limitations**

This response was generated by an AI system analyzing medical research. While we strive for accuracy:
- AI cannot examine you physically
- AI cannot consider all aspects of your health history
- AI cannot replace clinical judgment
- Medical knowledge continues to evolve

A healthcare provider can offer personalized evaluation and care."""


# =============================================================================
# Disclaimer Functions
# =============================================================================

def get_disclaimer_for_risk_level(risk_level: str) -> str:
    """
    Get the appropriate disclaimer based on risk level.
    
    Args:
        risk_level: One of "normal", "monitor", "concerning", "urgent"
        
    Returns:
        Appropriate disclaimer text
    """
    risk_level = risk_level.lower()
    
    if risk_level == "urgent":
        return URGENT_DISCLAIMER
    elif risk_level == "concerning":
        return f"{STANDARD_MEDICAL_DISCLAIMER}\n\n{RESEARCH_CITATION_DISCLAIMER}"
    else:
        return STANDARD_MEDICAL_DISCLAIMER


def get_contextual_disclaimers(
    is_pregnant: bool = False,
    is_first_query: bool = False,
    include_sensitivity: bool = True,
) -> str:
    """
    Build contextual disclaimers based on user situation.
    
    Args:
        is_pregnant: Whether user is pregnant
        is_first_query: Whether this is user's first query
        include_sensitivity: Whether to include sensitivity disclaimer
        
    Returns:
        Combined disclaimer text
    """
    parts = []
    
    if is_pregnant:
        parts.append(PREGNANCY_DISCLAIMER)
    
    if is_first_query and include_sensitivity:
        parts.append(SENSITIVITY_DISCLAIMER)
    
    parts.append(LIMITATION_DISCLAIMER)
    
    return "\n".join(parts)


def format_complete_disclaimer(
    risk_level: str,
    is_pregnant: bool = False,
    is_first_query: bool = False,
) -> str:
    """
    Format a complete disclaimer section for a response.
    
    Args:
        risk_level: The assessed risk level
        is_pregnant: Whether user is pregnant
        is_first_query: Whether this is user's first query
        
    Returns:
        Complete formatted disclaimer section
    """
    main_disclaimer = get_disclaimer_for_risk_level(risk_level)
    
    # Add pregnancy disclaimer if applicable
    if is_pregnant:
        main_disclaimer = f"{PREGNANCY_DISCLAIMER}\n\n{main_disclaimer}"
    
    return main_disclaimer


# =============================================================================
# Inline Disclaimer Snippets
# =============================================================================

INLINE_DISCLAIMERS: Final[dict[str, str]] = {
    "general_advice": (
        "(*This is general information and may not apply to your specific situation.*)"
    ),
    "consult_provider": (
        "(*Please discuss with your healthcare provider for personalized advice.*)"
    ),
    "research_based": (
        "(*Based on available research; individual experiences may vary.*)"
    ),
    "not_diagnosis": (
        "(*This is not a diagnosis; a healthcare provider can properly evaluate your condition.*)"
    ),
    "seek_care": (
        "(*If symptoms persist or worsen, please seek medical attention.*)"
    ),
}


def get_inline_disclaimer(key: str) -> str:
    """Get an inline disclaimer by key."""
    return INLINE_DISCLAIMERS.get(key, INLINE_DISCLAIMERS["general_advice"])


# =============================================================================
# Footer for All Responses
# =============================================================================

RESPONSE_FOOTER: Final[str] = """---

📋 **Response ID**: {response_id}
🕐 **Generated**: {timestamp}
📊 **Risk Level**: {risk_level}

*If you have concerns about your results, please don't hesitate to contact a healthcare provider.*"""


def format_response_footer(
    response_id: str,
    timestamp: str,
    risk_level: str,
) -> str:
    """Format the response footer with metadata."""
    return RESPONSE_FOOTER.format(
        response_id=response_id,
        timestamp=timestamp,
        risk_level=risk_level.upper(),
    )

